# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('thumbnail', models.CharField(max_length=250)),
                ('creator_name', models.CharField(max_length=250)),
                ('creator_profile_url', models.CharField(max_length=250)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
